default_install_hook_types: [pre-commit, pre-push]
fail_fast: true

repos:
-   repo: local
    hooks:
    - id: lint
      name: Run Lint
      language: system
      entry: rake swift:lint
      stages: [pre-commit]
    - id: build
      name: Run Build
      language: system
      entry: bash -c 'output=$(rake swift:build 2>&1 > /dev/null); if [ $? -ne 0 ]; then echo "$output"; fi'
      stages: [pre-push]
