# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Swift Build

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Xcode ${{ matrix.xcode }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15]
        xcode: ["16"]
    env:
        GITHUB_TOKEN: ${{ secrets.RAK_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Lint
        run: rake swift:lint
      - name: Build
        run: rake swift:build
